# --------------------
#    !!!WARNING!!!
# --------------------
# This file is autogenerated, any changes will not be retained after next
# generation.
#
# @brief In this file are Source, Param, Group dictionaries.
# /

sourceIDtoName = dict()
sourceIDtoName[0] = "DEFAULT"
sourceIDtoName[1] = "MPPT_CONTROLLER_1"
sourceIDtoName[2] = "MPPT_CONTROLLER_2"
sourceIDtoName[3] = "LIFEPO4_CONTROLLER_1"
sourceIDtoName[4] = "LIFEPO4_CONTROLLER_2"
sourceIDtoName[5] = "MPPT_1"
sourceIDtoName[6] = "MPPT_2"
sourceIDtoName[7] = "MPPT_3"
sourceIDtoName[8] = "MPPT_4"
sourceIDtoName[9] = "LIFEPO4_1"
sourceIDtoName[10] = "LIFEPO4_2"
sourceIDtoName[11] = "LIFEPO4_3"
sourceIDtoName[12] = "LIFEPO4_4"
sourceIDtoName[13] = "PUMPS_CONTROLLER"
sourceIDtoName[14] = "CPB_CONTROLLER"
sourceIDtoName[15] = "PiBox"
sourceIDtoName[16] = "GPS_CONTROLLER"


nameToSourceID = dict()
nameToSourceID["DEFAULT"] = 0
nameToSourceID["MPPT_CONTROLLER_1"] = 1
nameToSourceID["MPPT_CONTROLLER_2"] = 2
nameToSourceID["LIFEPO4_CONTROLLER_1"] = 3
nameToSourceID["LIFEPO4_CONTROLLER_2"] = 4
nameToSourceID["MPPT_1"] = 5
nameToSourceID["MPPT_2"] = 6
nameToSourceID["MPPT_3"] = 7
nameToSourceID["MPPT_4"] = 8
nameToSourceID["LIFEPO4_1"] = 9
nameToSourceID["LIFEPO4_2"] = 10
nameToSourceID["LIFEPO4_3"] = 11
nameToSourceID["LIFEPO4_4"] = 12
nameToSourceID["PUMPS_CONTROLLER"] = 13
nameToSourceID["CPB_CONTROLLER"] = 14
nameToSourceID["PiBox"] = 15
nameToSourceID["GPS_CONTROLLER"] = 16


paramIDtoName = dict()
paramIDtoName[0] = "DEFAULT"
paramIDtoName[1] = "HEARTBEAT"
paramIDtoName[2] = "LIFEPO4_GENERAL"
paramIDtoName[3] = "LIFEPO4_CELLS_1"
paramIDtoName[4] = "LIFEPO4_CELLS_2"
paramIDtoName[5] = "LIFEPO4_CELLS_3"
paramIDtoName[6] = "PUMPS_GENERAL"
paramIDtoName[7] = "EMBEDDED_BUS_DATA"
paramIDtoName[8] = "POWER_BUS_DATA"
paramIDtoName[9] = "PV_DATA"
paramIDtoName[10] = "MPPT_CHARGER_DATA"
paramIDtoName[11] = "YIELD_DATA"
paramIDtoName[12] = "GEODETIC_POSITION_1"
paramIDtoName[13] = "GEODETIC_POSITION_2"
paramIDtoName[14] = "NED_VELOCITY"
paramIDtoName[15] = "NED_HEADING"


nameToParamID = dict()
nameToParamID["DEFAULT"] = {'GroupID': 0, 'ParamID': 0, 'Priority': 0}
nameToParamID["HEARTBEAT"] = {'GroupID': 0, 'ParamID': 1, 'Priority': 7}
nameToParamID["LIFEPO4_GENERAL"] = {'GroupID': 1, 'ParamID': 2, 'Priority': 4}
nameToParamID["LIFEPO4_CELLS_1"] = {'GroupID': 1, 'ParamID': 3, 'Priority': 7}
nameToParamID["LIFEPO4_CELLS_2"] = {'GroupID': 1, 'ParamID': 4, 'Priority': 7}
nameToParamID["LIFEPO4_CELLS_3"] = {'GroupID': 1, 'ParamID': 5, 'Priority': 7}
nameToParamID["PUMPS_GENERAL"] = {'GroupID': 0, 'ParamID': 6, 'Priority': 5}
nameToParamID["EMBEDDED_BUS_DATA"] = {
    'GroupID': 0, 'ParamID': 7, 'Priority': 3}
nameToParamID["POWER_BUS_DATA"] = {'GroupID': 0, 'ParamID': 8, 'Priority': 3}
nameToParamID["PV_DATA"] = {'GroupID': 2, 'ParamID': 9, 'Priority': 5}
nameToParamID["MPPT_CHARGER_DATA"] = {
    'GroupID': 2, 'ParamID': 10, 'Priority': 7}
nameToParamID["YIELD_DATA"] = {'GroupID': 2, 'ParamID': 11, 'Priority': 7}
nameToParamID["GEODETIC_POSITION_1"] = {
    'GroupID': 0, 'ParamID': 12, 'Priority': 7}
nameToParamID["GEODETIC_POSITION_2"] = {
    'GroupID': 0, 'ParamID': 13, 'Priority': 7}
nameToParamID["NED_VELOCITY"] = {'GroupID': 0, 'ParamID': 14, 'Priority': 6}
nameToParamID["NED_HEADING"] = {'GroupID': 0, 'ParamID': 15, 'Priority': 7}


groupIDtoName = dict()
groupIDtoName[0] = "DEFAULT"
groupIDtoName[1] = "LIFEPO4_DATA"
groupIDtoName[2] = "MPPT_DATA"


nameToGroupID = dict()
nameToGroupID["DEFAULT"] = 0
nameToGroupID["LIFEPO4_DATA"] = 1
nameToGroupID["MPPT_DATA"] = 2
